import type { Metadata } from "next";
import {Space_Grotesk} from "next/font/google";
import "./globals.css";
import Navbar from "./Components/Navbar";

const font = Space_Grotesk({
  subsets: ["latin"],
  weight: ["300", "400", "500", "700"],
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${font.className}`}
      >
        <Navbar/>
        {children}
      </body>
    </html>
  );
}
